### PR TITLE
Support for FS2 0.10

### PR DESCRIPTION
**Pull request by BenFradet**
I think we should wait for a non-milestone 0.10 release from FS2, hopefully that'll happen before circe 0.9 :+1:

### CODE REVIEW

**Comment by aeons** [comment]
As in #15 , it might make sense to add `*ParserS` variants that work on `fs2.Segment`s.

**Comment by BenFradet** [comment]
@aeons good idea :+1:

**Comment by BenFradet** [comment]
@aeons do you want to open a PR against this branch for the segment related operations?

**Comment by aeons** [comment]
Any chance this could be merged and released as a snapshot?

**Comment by BenFradet** [comment]
I'm happy to merge it, @travisbrown would you be able to cut a 0.9.0-M2?

**Comment by travisbrown** [comment]
@BenFradet Sure, just let me know when you're ready.

**Comment by BenFradet** [comment]
@travisbrown ready :+1:, thanks a lot

**Comment by aeons** [comment]
Cool, thanks.

**Pull request merged**
